### ISSUE TITLE
[request] Macro Command to Reload Overlays

### ISSUE THREAD

**Issue by natyusha** [Styr1x/Browsingway#17]
Would it be possible to add a command to reload overlays? Something along the lines of  `/bw inlay inlayCommandName reload` would be quite useful. Apologies if this is already possible.

**Comment by Styr1x** [comment]
Sorry for the late response, getting swamped with rl work latetly.

Its not currently possible, but its something I'm missing, too, so I'll add it to my todo list!

**Comment by natyusha** [comment]
I should mention that this functionality can be replicated by using `/bw inlay inlayCommandName url currentlyUsedURL` and it will 'reload' the overlay. This isn't super intuitive but it also makes this request somewhat unnecessary.
