### ISSUE TITLE
[Question] How to have it use same fonts as ACT overlay?

### ISSUE THREAD

**Issue by Theletha** [Styr1x/Browsingway#20]
im using the raid alerts but its not the same font. Is there a way to replicate it? It is using the same .CSS string, but not sure where the fonts are stored. 
https://i.imgur.com/lMlP01a.png

**Comment by Styr1x** [comment]
I'm not sure, it should use the correct font, it basically should look identical to the browser version. Is the font also broken in Chrome / Firefox?

**Comment by Theletha** [comment]
Yes it look the same as in browsingway

**Comment by gucciBane** [comment]
I think I have the same issue. Cactbot displays custom CSS when I use it normally, but ignores it when setup through Browsingway. Here's a picture of the straight-ACT version and the Browsingway layered on top of each other.

![Screenshot 2022-05-09 185516](https://user-images.githubusercontent.com/49180180/167521530-e4c13363-40fd-450f-bc75-008a029712f3.png)

**Comment by Styr1x** [comment]
Its not really an Browsingnway issue but rather a feature of Cactbot that they implemented. When you add custom CSS to their folder it gets automatically injected into their chromium window.

Something akin to that will be added to Browsingway down the line, but it will not work the same as it does in Cactbot, meaning you will have to select the file-to-be-injected from inside Browsingway.

**Comment by Theletha** [comment]
> 

wait so we can get it working? 
If so could you explain a bit easier so i can try and do it?

**Comment by Theletha** [comment]
https://github.com/quisquous/cactbot/issues/4868
