### ISSUE TITLE
Is it possible to use Kagerou with the image I set on ACT?

### ISSUE THREAD

**Issue by YunoSuzuki** [Styr1x/Browsingway#22]
If so, how?

**Comment by Styr1x** [comment]
It should be, what exaclty isn't working?
https://github.com/Styr1x/Browsingway#act-support

**Comment by YunoSuzuki** [comment]
The tracker is working perfectly, I just wanted to use it with the custom image I set on the Kagerou configuration. Is it possible?

**Comment by Styr1x** [comment]
I don't know how Kagerou does it, but if setting the image works in a browser it should also work in Browsingway. If it doesn't work in e.g. Chrome it also won't work in Browsingway. What you can always do is just patch the local files of the overlay, like physically change the images or css files. Will get overwritten by an update tough, but until then it sticks.

In the future https://github.com/Styr1x/Browsingway/issues/21 might make this a bit easier.
