### ISSUE TITLE
7/13/22 Patch caused CACBOT and overlays to stopworking w/ this addon

### ISSUE THREAD

**Issue by Reidlos65** [Styr1x/Browsingway#24]
Maybe its just me? Been working fine for several patchs, but i play fullscreen due to a super resolution upscale, and it seems Cacbot updated and altets are working but now showing on my screen thru the overlay anymore.

**Comment by Styr1x** [comment]
It works for me; Cactbot and the FFXIV ACT Plugin itself require updates to work with 6.18h, maybe something went wrong on that side? Does it work without Browsingway?
