### ISSUE TITLE
Reload command?

### ISSUE THREAD

**Issue by gucciBane** [Styr1x/Browsingway#26]
If this exists already, forgive, I apparently can't read.

Cactbot doesn't seem to want to kick in without a reload every time I start the game, so I've got to go into the setup and hit 'Reload.' Assuming this is intended behaviour, is there/could a command to reload the overlay be added?

Thanks

**Comment by natyusha** [comment]
Refer to this issue for a workaround https://github.com/Styr1x/Browsingway/issues/17

**Comment by DAOWAce** [comment]
To clarify, are you saying ACT's inlays do not show up until you 'reload' it in browsingway?

**Comment by gucciBane** [comment]
Right. The linked discussion helped me workaround it.

**Comment by DAOWAce** [comment]
Okay, it seems to be the same issue I'm having as well.

The workaround I discovered was to run ACT **before** starting FFXIV.   The reload command didn't seem to work, but it did now for some reason.  Assuming cactbot's timeline has to fully stop before it can be displayed again?

But yeah this is what I originally came to post before looking in this issue, as I don't know why Browsingway isn't registering cactbot's overlay when ACT starts up.

**Comment by Styr1x** [comment]
A dedicated reload command was added with a939df2. It also adds an option to automatically enable/disable ACT specific overlays depending on if ACT is running or not. This way overlays will be loaded when ACT is started and closed once ACT exits.
