### ISSUE TITLE
Cactbot volume

### ISSUE THREAD

**Issue by Cameron6897** [Styr1x/Browsingway#27]
Sorry if this is a stupid question.. But is it possible lower the volume of Cactbot alerts when using it in Browsingway? I hate borderless window input lag and am hoping I can get everything set up the way I want it in fullscreen.

**Comment by Styr1x** [comment]
Unfortunately CEF doesn't have native support to do this. There where workarounds changing per process audio, but in newer CEF versions this doesn't really work at all.

Only viable solution I know is to inject JavaScript code that tries to find the audio playing parts in the DOM and apply volume there. Overall I think that is something ACT/Cactbot should fix on their side, e.g. make volume settings apply correct volume inside their web content. I don't use it myself, but it seems like they are volume settings inside Cactbot. Did you try those? If they don't work you might want to open an issue on their side to fix it.
