### ISSUE TITLE
[REQUEST] Possible to run on DXVK?

### ISSUE THREAD

**Issue by X3ME15** [Styr1x/Browsingway#32]
Hello and good day,

I would like to ask if there's a possibility to run the plugin whenever I'm running FFXIV in DXVK fullscreen? 
I tried to run it but getting a SharpDX error. Can the renderer be altered to run on DXVK or is it the chromium asset locked to render only in d3d? 
Any input and suggestions are appreciated. 

Thank you,
X3ME15

![image_2023-02-05_194503335](https://user-images.githubusercontent.com/124500809/216816761-088cf981-8e22-4346-889d-ab13e871c36f.png)

**Comment by Styr1x** [comment]
DXVK doesn't implement shared textures, thats why it doesn't work. The workaround for that is transporting the rendered texture / image through shared mem, but that render path is currently also broken (and slower than shared texture). So there isn't much you can do at this point I'm afraid.

**Comment by X3ME15** [comment]
@Styr1x 

Thank you for the quick reply and the clarification. I was hoping it can be  done considering DXVK has great performance uplift when using FFXIV. 
Anyway, great job on the plugin and I'm gonna follow the progress of this project. 😉👍
