### ISSUE TITLE
confirmation

### ISSUE THREAD

**Issue by Yarukon** [Styr1x/Browsingway#35]
https://github.com/Styr1x/Browsingway/blob/f88892f6b57a103a0c96fa1d607114ca928a4f00/Browsingway/ActHandler.cs#L32
is this line should be use ' && ' instead of ' || ' ?

**Comment by Styr1x** [comment]
No, its "either Main Window is up, or 5 seconds have passed since process creation". In case ACT is run without window (tray)

**Comment by Yarukon** [comment]
ok thanks
