### ISSUE TITLE
[Issue] Possible layering issue with G Shade

### ISSUE THREAD

**Issue by RainerGevers** [Styr1x/Browsingway#4]
[Issue]
Browser window causes G Shade to not be applied to menus beneath/above it. This happens only to menus and not the game itself. It affects Dalmund and Game menus equally. Screenshot show the `Maya Happiness Gameplay` filter applied.

If at all possible. Could you check if it's possible to change the depth of the plugin to be either below menus or above them so as not to cause boxes on screen where G Shade does not apply?

<img width="1344" alt="ffxiv_07012022_215540_872" src="https://user-images.githubusercontent.com/32453861/148644862-fa183d2c-8358-45ad-a88d-2e32020d13a8.png">

**Comment by Styr1x** [comment]
I'm not a G Shade user myself, but I will try to fix this after the plugin rewrite I'm doing right now.

**Comment by Styr1x** [comment]
Cali666 in Discord pointed to the solution for this problem: https://goatcorp.github.io/faq/dalamud_troubleshooting.html#q-reshade-and-its-variants-dont-work-or-dalamud-ui-fails
