### ISSUE TITLE
IINACT Cactbot doesn't work until I disable and enable the inlays

### ISSUE THREAD

**Issue by rechington** [Styr1x/Browsingway#40]
After every time I start the game I have to disable and enable the Cactbot inlays to get them working. Not sure if this is an IINACT or Browsingway issue, but if I open the URLs in a browser they show up there. Only "Click Through" is enabled for the inlays.

**Comment by jeremyrogers** [comment]
I can confirm this is happening to me too, but it doesn't seem to be consistent. I think it's a race condition where Browsingway isn't guaranteed to draw the overlays after IINACT is ready. I thought that maybe this commit would fix that, but this may have just been for the "ACT/IINACT Optimization" option: https://github.com/Styr1x/Browsingway/commit/5b6c7af16cad9ecd849dfb9e349fc18cb2a2460c

This was also referenced in an IINACT issue: https://github.com/marzent/IINACT/issues/46. I can provide Dalamud logs if they'd help debug

**Comment by Styr1x** [comment]
It is working for me, but I might have an odd installation of IINACT where I use the local file urls and not the IINACT proxy URLs.

Browsingway should enable the Overlays only after IINACT IPC said ready, I wonder how that can end up with a race condition.

I guess you are using Cactbot with the URL that IINACT generated? I'll look into this tomorrow before raid. I also check when exactly IINACT sets its ready state, maybe thats a tad to early, also.

**Comment by jeremyrogers** [comment]
Yes, I'm using the IINACT proxy URLs. If there was a good way to keep the local files up to date automatically (other than through ACT), I would probably use local files too.

**Comment by Styr1x** [comment]
So I tried it and it works as expected on my side

Just to make sure: You did enable "ACT/IINACT optimizations" for the overlays in question? Because this is the option that automatically loads and unloads the overlay if ACT or IINACT is ready or not.

E.g. without that option on it is expected to have to reload certain overlays manually, as they don't have reconnect code in their Javascript and thus stop working when they can't connect to ACT's or IINACT's Websocket server.

**Comment by rechington** [comment]
Oh! I didn't have those on, as I thought it was optional. At first it didn't work with it on either, but then I just had to wait for a bit and it started working. It makes sense now. Thanks! Maybe it should be included in the popup text? I think it's a bit unclear.

**Comment by jeremyrogers** [comment]
Ah! Okay, that makes sense. Yup, looks like that fixed it on my end too. Thank you!

**Comment by Styr1x** [comment]
Point taken, I'll improve the help text next time I push a new version!
