### ISSUE TITLE
[Feature Request] Chromium Extension Support

### ISSUE THREAD

**Issue by means2014** [Styr1x/Browsingway#49]
Since the browser under-the-hood is Chromium, it would be great to be able to use extensions like uBlock Origin (or at least Lite, I haven't figured out the Manifest v3 stipulations for Chromium distributions not helmed by Alphabet).  

I don't know what kind of effort it would take to make this happen, but I'd be happy to lend a hand on it once I get my Dev class to level 90.

**Comment by Styr1x** [comment]
CEF does not implement / support all of Chromiums APIs, more specific the extension support is very limited / nonexistent.
You can make certain extensions work if they use a limited API set or you implement them yourself, but you can't just download an extension from the store and it will work.
Adblocker was requested before, so I'd accept a PR if someone implements all required APIs for it / makes it work. See https://github.com/cefsharp/CefSharp/issues/2497 for details.
