### ISSUE TITLE
[Question] Act overlays

### ISSUE THREAD

**Issue by markuznw** [Styr1x/Browsingway#5]
Hello there and thanks for your work. Can this be used for act overlays for meter and such? I get it like that from the docs but don't get how to make it work. Overlays are set and visible but they never get updated from ffxiv plugin in act. Do i need to set something?

Thank you and sorry for the stupid question :)

**Comment by Styr1x** [comment]
Yes, this plugin was made with ACT overlays in mind. You have to enable to WS Server in ACT and then you can just copy the URL it generates for you. See the attached screenshot.
![image](https://user-images.githubusercontent.com/569324/148692825-f29e41ae-cec5-4144-974f-394e14ec108a.png)

**Comment by markuznw** [comment]
Ahhhh didn't know that it generated an url with html already served, thank you, so kind <3

Closing as solved, thanks again!!!!
