### ISSUE TITLE
unable to download dependencies

### ISSUE THREAD

**Issue by dalamudx** [Styr1x/Browsingway#50]
unable to download dependencies after update to 1.6,it hangs here about 30mins,can not disable it,and there are no speed on speedmoniter app.
![image](https://github.com/Styr1x/Browsingway/assets/88395653/e5ea42d8-79d5-4377-b487-a6a59d6e2e76)
but i can download it from git using wget(built in powershell)🥲

**Comment by Styr1x** [comment]
Odd, but as a workaround you can do it manually. Extract the content of the dependency-zip to %APPDATA%\XIVLauncher\pluginConfigs\Browsingway\dependencies\cef

**Comment by dalamudx** [comment]
> Odd, but as a workaround you can do it manually. Extract the content of the dependency-zip to %APPDATA%\XIVLauncher\pluginConfigs\Browsingway\dependencies\cef

thanks,it works!
btw,if browsingway deleted,keep cef folder empty,install browsingway first,then exit the game and place cef files into the folder,reopen the game.
or you will get an error while install browsingway.
