### ISSUE TITLE
Render process crashed - will restart asap

### ISSUE THREAD

**Issue by Menci** [Styr1x/Browsingway#51]
The log window is messed up with:

```
00:42:32.958 ERR | [Browsingway] Render process crashed - will restart asap
00:42:32.989 ERR | [Browsingway] [Render]: You must install or update .NET to run this application.
00:42:32.989 ERR | [Browsingway] [Render]: 
00:42:32.989 ERR | [Browsingway] [Render]: App: D:\FFXIV\XIVLauncherCN\Roaming\installedPlugins\Browsingway\1.5.6.0\renderer\Browsingway.Renderer.exe
00:42:32.989 ERR | [Browsingway] [Render]: Architecture: x64
00:42:32.990 ERR | [Browsingway] [Render]: Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
00:42:32.990 ERR | [Browsingway] [Render]: .NET location: C:\Users\Menci\AppData\Roaming\XIVLauncher\runtime
00:42:32.990 ERR | [Browsingway] [Render]: 
00:42:32.990 ERR | [Browsingway] [Render]: The following frameworks were found:
00:42:32.990 ERR | [Browsingway] [Render]:   8.0.0 at [C:\Users\Menci\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App]
00:42:32.990 ERR | [Browsingway] [Render]: 
00:42:32.990 ERR | [Browsingway] [Render]: Learn more:
00:42:32.990 ERR | [Browsingway] [Render]: https://aka.ms/dotnet/app-launch-failed
00:42:32.990 ERR | [Browsingway] [Render]: 
00:42:32.990 ERR | [Browsingway] [Render]: To install missing framework, download:
00:42:32.990 ERR | [Browsingway] [Render]: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=win-x64&os=win10
00:42:32.991 INF | [Browsingway] [Render]: 
00:42:32.991 ERR | [Browsingway] [Render]: 
```

I have both .NET 7.0 and 8.0 installed.

**Comment by Styr1x** [comment]
You have an old version of Browsingway, 1.6.0.0 is the current one that also fixes your problem (check for updates inside Dalamud).

**Comment by Menci** [comment]
Yes, I found there're 1.6.0.0 tag. But Dalamud don't provide me an update...

![image](https://github.com/Styr1x/Browsingway/assets/11341955/8e7f68a4-59cf-4c2c-9405-ba146bf887d8)

**Comment by Menci** [comment]
```
01:04:01.388 INF | [Browsingway] [Render]: Render process running.
01:04:01.405 INF | [Browsingway] [Render]: Watching parent PID 17432
01:04:02.077 ERR | [Browsingway] [Render]: SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.
01:04:02.077 ERR | [Browsingway] [Render]: 
01:04:02.078 ERR | [Browsingway] [Render]:    at SharpDX.Result.CheckError()
01:04:02.083 ERR | [Browsingway] [Render]: Unhandled exception. SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.
01:04:02.083 ERR | [Browsingway] [Render]: 
01:04:02.083 ERR | [Browsingway] [Render]:    at SharpDX.Result.CheckError()
01:04:02.083 ERR | [Browsingway] [Render]:    at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
01:04:02.083 ERR | [Browsingway] [Render]:    at SharpDX.Direct3D11.Device..ctor(Adapter adapter, DeviceCreationFlags flags)
01:04:02.083 ERR | [Browsingway] [Render]:    at Browsingway.Renderer.DxHandler.Initialise(Int64 adapterLuid) in C:\Users\Menci\Projects\Browsingway\Browsingway.Renderer\DxHandler.cs:line 37
01:04:02.083 ERR | [Browsingway] [Render]:    at Browsingway.Renderer.Program.Run(RenderParams args) in C:\Users\Menci\Projects\Browsingway\Browsingway.Renderer\Program.cs:line 53
01:04:02.083 ERR | [Browsingway] [Render]:    at Browsingway.Renderer.Program.Main(String[] rawArgs) in C:\Users\Menci\Projects\Browsingway\Browsingway.Renderer\Program.cs:line 38
01:04:03.156 INF | [LOCALPLUGIN] Unloading Browsingway.dll
01:04:03.469 INF | [Browsingway] [Render]: 
01:04:03.469 ERR | [Browsingway] [Render]: 
01:04:03.474 ERR | [Command] Command /bw not found.
01:04:04.476 INF | [LOCALPLUGIN] Finished unloading Browsingway.dll
```

Manually built v1.6.0.0 throws this.

**Comment by Styr1x** [comment]
I checked the CN PluginDist (https://github.com/ottercorp/PluginDistD17/blob/main/stable/Browsingway/Browsingway.json), its on the old version, while the international one is up2date (https://github.com/goatcorp/PluginDistD17/blob/main/stable/Browsingway/Browsingway.json). I have no clue how those get updated / merged.

Not sure why your manual build doesn't work, but you could try the Plogin CI build one: https://github.com/goatcorp/PluginDistD17/blob/main/stable/Browsingway/latest.zip
Its the first time I've seen this error.

**Comment by Menci** [comment]
CI 1.6.0.0 throws error without any logs on my CN ver game:

![image](https://github.com/Styr1x/Browsingway/assets/11341955/d00d9dcb-c7a4-49bb-9fb5-26e4ed8d030c)

I also found the cause of the issue my encountered: https://github.com/sharpdx/SharpDX/issues/858#issuecomment-282347213. Building removing the Debug flag resulting in the same error as above.

**Comment by Menci** [comment]
![image](https://github.com/Styr1x/Browsingway/assets/11341955/b34405e4-5123-40f2-a3b6-f021e3a08304)

Yes, 1.6.0.0 works on the intl ver game. So let me keep two game clients open and check my DPS on this side...

**Comment by Styr1x** [comment]
Did you switch to a .net8 build on the CN client manually? Like, CN does still seem to use .net 7 on its main branch and this should work with the 'old' version of BW in the CN repo.

**Comment by Menci** [comment]
Yes. I also just found that Dalamud global has been upgraded to .NET 8. However, the old version of BrowsingWay fails to download dependencies (404 not found). Where can I find the CEF build you use?

**Comment by Styr1x** [comment]
Hmm 1.5.6 should use this one: https://github.com/Styr1x/Browsingway/releases/download/cef-binaries/cefsharp-121.3.13+g5c4a81b+chromium-121.0.6167.184.zip

**Comment by Menci** [comment]
1.5.6 doesn't work. 1.5.5 needs `117.2.2+ge80c977+chromium-117.0.5938.132` which is not found...

**Comment by Styr1x** [comment]
Yeah, 1.5.5 dependencies where pruned, sorry.

**Comment by Menci** [comment]
Do you have a copy locally? Could you post that here?

**Comment by Styr1x** [comment]
I checked, its the one version I've seen to have lost. Its easy to recreate, but the checksum will not match anymore.
