### ISSUE TITLE
Overlay settings not being saved

### ISSUE THREAD

**Issue by 0kie** [Styr1x/Browsingway#55]
I had this problem happen a few times before but since the dawntrail update every time I reset the game or even disable and re-enable the plugin my overlay settings will be reset to default. (not the settings in browsingway configs /bw config)

For example, I add Ikegami dps meter, change the theme, layout and the info it shows. Once I reset the game or even simply toggle the plugin on/off it will not be saved and will behave as it is the first time booting the overlay, even showing the changelog.

**Comment by Styr1x** [comment]
It seems to be the new Chromium version which breaks storage related stuff, working on it.
