### ISSUE TITLE
ACT Overlay Plugin

### ISSUE THREAD

**Issue by Lightningitin** [Styr1x/Browsingway#7]
hey i wanted to use ACT dps meter for the first time as i saw ur plugin. im using Fullscreen only as im losing a huge amount of performance when i play in borderless mode so i never could test out the dps meter. ive installed your plugin and installed ACT with the "kagerou" overlay. i cant seem to figure out what to put inside of the asked " URL " that he wants frome me. i tried couple of paths but i end up in one of my path folders. hope u can help me out here. 

thanks and have a great day

**Comment by Styr1x** [comment]
Hey, does this help? https://github.com/Styr1x/Browsingway/issues/5

**Comment by Lightningitin** [comment]
yes this was the answer i was looking for! thank you so much!
