### ISSUE TITLE
[QUESTION] Windowed Borderless G-sync

### ISSUE THREAD

**Issue by Iaotle** [Styr1x/Browsingway#9]
If I'm playing with G-sync enabled on windowed borderless this doesn't help me right?

**Comment by Styr1x** [comment]
Yeah, if your G-SYNC experience and frametimes are satisfactory in borderless mode there would be no point in using this plugin.
Its mainly for ppl that either need a browser ingame or want to display ACT overlays while the game runs in exclusive fullscreen mode.
